"""
decisions.py — Architecture Decision Record writer
──────────────────────────────────────────────────
Every value collected (from infra.yaml, interactive prompt, AI extraction,
or rule match) is logged here with source, reason, and timestamp.

decisions.md is as important as the IaC itself — it is the audit trail
for every infrastructure choice made during scaffold generation.

Format per problem statement spec (section 4.3):
  ## field_name
  Decision: value
  Decided: 2026-05-22
  Source: interactive prompt | infra.yaml | rule | default | ai extraction
  Reason: "explanation"
  Revisit: optional note when conditions might change
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

_DEFAULT_PATH = Path(".infra/decisions.md")


def _ensure_file(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(
            "# Infrastructure Decisions\n\n"
            "> Generated by devops-scaffold-tool.  \n"
            "> Every infrastructure choice made during this scaffold run is recorded here.\n"
            "> Do not delete this file — it is the rationale layer for the generated IaC.\n\n",
            encoding="utf-8",
        )


def log_run_header(project_name: str, path: Path = _DEFAULT_PATH) -> None:
    """Write a timestamped run separator at the top of a new scaffold run."""
    _ensure_file(path)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    with open(path, "a", encoding="utf-8") as f:
        f.write(f"\n---\n\n## Scaffold Run — {ts}  |  project: {project_name}\n")


def log_decision(
    field:   str,
    value,
    source:  str,
    reason:  str,
    revisit: Optional[str] = None,
    path:    Path = _DEFAULT_PATH,
) -> None:
    """
    Log one decision entry.

    source values:
      "infra.yaml"         — read directly from the input file
      "interactive prompt" — collected via CLI question
      "ai extraction"      — extracted from --describe text by AI
      "rule"               — determined automatically by the rules engine
      "default"            — fell back to a built-in default
    """
    _ensure_file(path)
    ts    = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"\n### {field}",
        f"",
        f"Decision: {value}",
        f"Decided:  {ts}",
        f"Source:   {source}",
        f'Reason:   "{reason}"',
    ]
    if revisit:
        lines.append(f"Revisit:  {revisit}")
    lines.append("")
    with open(path, "a", encoding="utf-8") as f:
        f.write("\n".join(lines))


def log_warning(message: str, path: Path = _DEFAULT_PATH) -> None:
    """Log an anti-pattern warning."""
    _ensure_file(path)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    with open(path, "a", encoding="utf-8") as f:
        f.write(f"\n> **WARNING** ({ts}): {message}\n")


def log_section(title: str, path: Path = _DEFAULT_PATH) -> None:
    """Write a section heading (e.g. 'Compute Decisions', 'Warnings')."""
    _ensure_file(path)
    with open(path, "a", encoding="utf-8") as f:
        f.write(f"\n#### {title}\n")
